/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccns_practicals;

import java.math.BigInteger;
import java.util.Arrays;

/**
 *
 * @author Uditya
 */
public class Diffie_Hellman_Key_Exchange extends javax.swing.JFrame {

    BigInteger Q;
    BigInteger ALPHA;
    
    BigInteger XA;
    BigInteger XB;
    BigInteger YA;
    BigInteger YB;
    
    BigInteger one = new BigInteger("1");
    
    /**
     * Creates new form Diffie_Hellman_Key_Exchange
     */
    public Diffie_Hellman_Key_Exchange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        XA_value = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        YA_Value = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        KA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        YB_Value = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        KB = new javax.swing.JTextField();
        XB_Value = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        q_value = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Publc Key");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Diffie Hellman Key Exchange");

        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Private Key");

        YA_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YA_ValueActionPerformed(evt);
            }
        });

        jLabel6.setText("Secret Key");

        KA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KAActionPerformed(evt);
            }
        });

        jLabel2.setText("Private Key");

        jLabel4.setText("Publc Key");

        YB_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YB_ValueActionPerformed(evt);
            }
        });

        jLabel7.setText("Secret Key");

        KB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KBActionPerformed(evt);
            }
        });

        jLabel8.setText("USER A");

        jLabel9.setText("USER B");

        jLabel10.setText("q");

        Submit.setText("Generate Secret Key");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(YA_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(YB_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(XA_value, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel8)))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(XB_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(83, 83, 83))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(21, 21, 21)
                                .addComponent(KA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(384, 384, 384)
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)))
                        .addComponent(KB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(q_value, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Submit)
                        .addGap(287, 287, 287))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(XA_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(XB_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(30, 30, 30)
                .addComponent(Submit)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(YA_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(YB_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(KA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(KB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addGap(196, 196, 196))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        new Main_Page().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void YA_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YA_ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YA_ValueActionPerformed

    private void KAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KAActionPerformed

    private void YB_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YB_ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YB_ValueActionPerformed

    private void KBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KBActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        Generate_Secret_Key();
    }//GEN-LAST:event_SubmitActionPerformed

    
    void Initialize (BigInteger q, BigInteger xa, BigInteger xb) {
        Q = q;
        
        ALPHA = Primitive_Root(Q);
        System.out.println("\n\nalpha = " + ALPHA);
        
        XA = xa;
        XB = xb;
        
        Generate_Public_Key();
    }
    
    
    BigInteger Primitive_Root (BigInteger q) {
        BigInteger z[] = new BigInteger[q.subtract(one).intValue()];
        for (int i = 0; i < z.length; i++) {
            z[i] = new BigInteger(Integer.toString(i + 1));
        }
        
        for (int i = 2; true; i++) {
            BigInteger array[] = new BigInteger[q.subtract(one).intValue()];
            
            for (int j = 0; j < array.length; j++) {
                array[j] = (new BigInteger(Integer.toString(i))).pow(j + 1).mod(Q);
            }
            
            Arrays.sort(array);
            
            if (Arrays.equals(array, z)) {
                return new BigInteger(Integer.toString(i));
            }
        }
    }
    
    void Generate_Public_Key () {
        System.out.print("\n\nPublic Key of:");
        
        YA = ALPHA.pow(XA.intValue()).mod(Q);
        System.out.print("\n    User A:");
        System.out.print("\n\tYA = (Alpha ^ XA) mod q");
        System.out.print("\n\t   = (" + ALPHA + " ^ " + XA + ") mod " + Q);
        System.out.print("\n\t   = " + YA);
        
        YA_Value.setText(YA.toString());
        
        
        
        YB = ALPHA.pow(XB.intValue()).mod(Q);
        System.out.print("\n\n    User A:");
        System.out.print("\n\tYB = (Alpha ^ XB) mod q");
        System.out.print("\n\t   = (" + ALPHA + " ^ " + XB + ") mod " + Q);
        System.out.print("\n\t   = " + YB);
        
        YB_Value.setText(YB.toString());
    }
    
    
    
    void Generate_Secret_Key () {
        Initialize (new BigInteger(q_value.getText()), new BigInteger(XA_value.getText()), new BigInteger(XB_Value.getText()));
        
        
        System.out.print("\n\n\nSecret Key for:");
        
        BigInteger k1 = YB.pow(XA.intValue()).mod(Q);
        System.out.print("\n    User A:");
        System.out.print("\n\tK = (YB ^ XA) mod q");
        System.out.print("\n\t   = (" + YB + " ^ " + XA + ") mod " + Q);
        System.out.print("\n\t   = " + k1);
        
        KA.setText(k1.toString());
        
        
        
        BigInteger k2 = YA.pow(XB.intValue()).mod(Q);
        System.out.print("\n\n    User B:");
        System.out.print("\n\tK = (YA ^ XB) mod q");
        System.out.print("\n\t   = (" + YA + " ^ " + XB + ") mod " + Q);
        System.out.print("\n\t   = " + k2);
        
        KB.setText(k2.toString());
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diffie_Hellman_Key_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diffie_Hellman_Key_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diffie_Hellman_Key_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diffie_Hellman_Key_Exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diffie_Hellman_Key_Exchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KA;
    private javax.swing.JTextField KB;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField XA_value;
    private javax.swing.JTextField XB_Value;
    private javax.swing.JTextField YA_Value;
    private javax.swing.JTextField YB_Value;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField q_value;
    // End of variables declaration//GEN-END:variables
}
